

#define CONFIG_X86 1
#define CONFIG_LITTLE_ENDIAN 1
#define CONFIG_MULTITHREADING 1
#define CONFIG_PBUF_RX_READ_BUF_SIZE 2
#define CONFIG_MP_MAX_NUM_CPUS 1
#define CONFIG_NUM_COOP_PRIORITIES 10
#define CONFIG_NUM_PREEMPT_PRIORITIES 10
#define CONFIG_MAX_IRQ_LINES 48
#define CONFIG_SYS_CLOCK_TICKS_PER_SEC 1000
#define CONFIG_SYS_CLOCK_MAX_TIMEOUT_DAYS 1000
#define CONFIG_DCACHE_LINE_SIZE 32
#define CONFIG_MBOX 1
#define CONFIG_IPC_SERVICE_REG_BACKEND_PRIORITY 0

#define CONFIG_IPC_SERVICE_ICMSG_BOND_NOTIFY_REPEAT_TO_MS 100
#define CONFIG_IPC_SERVICE_BACKEND_ICMSG 1

#define ZTEST_UNITTEST 1
