TRACE_MARK(1, INIT)

TRACE_CALL(2, ICBMSG_SEND)
TRACE_CALL(3, ICBMSG_ALLOC)
TRACE_CALL(4, ICBMSG_SEND_BLOCK)
TRACE_CALL(5, ICBMSG_SEND_CONTROL_MESSAGE)
TRACE_CALL(6, ICBMSG_SEND_ICMSG)
TRACE_CALL(7, ICBMSG_SEND_MEMCPY)

TRACE_CALL(8, MBOX_CALLBACK)
TRACE_CALL(9, ICMSG_PROCESS)
TRACE_CALL(10, ICBMSG_CTRL_RECEIVED)
TRACE_CALL(11, ICBMSG_USER_CALLBACK)
TRACE_CALL(12, ICBMSG_RELEASE_TX)

TRACE_CALL(30, RP_SEND)
TRACE_CALL(31, RP_MBOX_SEND)
TRACE_CALL(32, RP_MBOX_CALLBACK)
TRACE_CALL(33, RP_CALLBACK_PROCESS)

TRACE_CALL(99, SYSTEM_IRQ)

TRACE_MARK(100, END)
TRACE_MARK(101, ICBMSG_BITARR_FREE)
TRACE_MARK(102, ICBMSG_SEM_GIVE)

TRACE_MARK(254, RETURN_ERROR)
TRACE_MARK(255, RETURN_OK)

