/*
 * Copyright (c) 2022 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_IPC_ICMSG_H_
#define ZEPHYR_INCLUDE_IPC_ICMSG_H_

#include <stddef.h>
#include <stdint.h>
#include <zephyr/kernel.h>
#include <zephyr/drivers/mbox.h>
#include <zephyr/ipc/ipc_service.h>
#include <zephyr/ipc/pbuf.h>
#include <zephyr/sys/atomic.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Icmsg IPC library API
 * @defgroup ipc_icmsg_api Icmsg IPC library API
 * @ingroup ipc
 * @{
 */

struct icmsg_config_t {
	// MBOXes
	struct mbox_dt_spec mbox_tx;
	struct mbox_dt_spec mbox_rx;
	// TX fifo buffer
	struct {
		uint32_t *buffer;
		uint32_t buffer_words;
	} tx;
	// RX fifo buffer
	struct {
		const uint32_t *buffer;
		uint32_t buffer_words;
	} rx;
	// Read-write control block in shared memory
	volatile struct
	{
		uint32_t tx_write_index;
		uint32_t rx_read_index;
		uint16_t local_session_req;
		uint16_t remote_session_ack;
		uint32_t _reserved;
	} *rw_ctrl;
	// Read-only control block in shared memory
	const volatile struct
	{
		uint32_t rx_write_index;
		uint32_t tx_read_index;
		union {
			// Two fields are grouped together allowing simultaneous read
			uint32_t session_handshake;
			struct {
				uint16_t remote_session_req;
				uint16_t local_session_ack;
			};
		};
		uint32_t _reserved;
	} *ro_ctrl;
	struct k_work_q *workq;
	bool yield_on_more_input;
	bool dedicated_workq; // todo: maybe combine into flags?
	void *rx_buffer; /* todo: receive buffer, associated with workqueue, since we will never
	                      use more than one per thread. And one for interrupts if needed.
			      We need to calculate maximum size from device tree.
			      */
	uint32_t rx_buffer_size;
};


struct icmsg_data_t {
	int state;
	// local copy of TX FIFO indexes
	struct
	{
		uint32_t read_index;
		uint32_t write_index;
	} tx;
	// local copy of RX FIFO indexes
	struct
	{
		uint32_t read_index;
	} rx;
	// Local session id
	uint32_t local_session;
	// Current remote session id or -1 if unknown.
	uint32_t remote_session;
	const struct icmsg_config_t *conf;
	/* Callbacks */
	const struct ipc_service_cb *cb;
	void *ctx;
	/* Spin lock*/
	struct k_spinlock lock;
	/* Work item */
	struct k_work work; // todo: depends on config
};

/** @brief Open an icmsg instance
 *
 *  Open an icmsg instance to be able to send and receive messages to a remote
 *  instance.
 *  This function is blocking until the handshake with the remote instance is
 *  completed.
 *  This function is intended to be called late in the initialization process,
 *  possibly from a thread which can be safely blocked while handshake with the
 *  remote instance is being performed.
 *
 *  @param[in] conf Structure containing configuration parameters for the icmsg
 *                  instance.
 *  @param[inout] dev_data Structure containing run-time data used by the icmsg
 *                         instance.
 *  @param[in] cb Structure containing callback functions to be called on
 *                events generated by this icmsg instance. The pointed memory
 *                must be preserved while the icmsg instance is active.
 *  @param[in] ctx Pointer to context passed as an argument to callbacks.
 *
 *
 *  @retval 0 on success.
 *  @retval -EALREADY when the instance is already opened.
 *  @retval other errno codes from dependent modules.
 */
int icmsg_open(const struct icmsg_config_t *conf,
	       struct icmsg_data_t *dev_data,
	       const struct ipc_service_cb *cb, void *ctx);

/** @brief Close an icmsg instance
 *
 *  Closing an icmsg instance results in releasing all resources used by given
 *  instance including the shared memory regions and mbox devices.
 *
 *  @param[in] conf Structure containing configuration parameters for the icmsg
 *                  instance being closed. Its content must be the same as used
 *                  for creating this instance with @ref icmsg_open.
 *  @param[inout] dev_data Structure containing run-time data used by the icmsg
 *                         instance.
 *
 *  @retval 0 on success.
 *  @retval other errno codes from dependent modules.
 */
int icmsg_close(const struct icmsg_config_t *conf,
		struct icmsg_data_t *dev_data);

/** @brief Send a message to the remote icmsg instance.
 *
 *  @param[in] conf Structure containing configuration parameters for the icmsg
 *                  instance.
 *  @param[inout] dev_data Structure containing run-time data used by the icmsg
 *                         instance.
 *  @param[in] msg Pointer to a buffer containing data to send.
 *  @param[in] len Size of data in the @p msg buffer.
 *
 *
 *  @retval Number of sent bytes.
 *  @retval -EBUSY when the instance has not finished handshake with the remote
 *                 instance.
 *  @retval -ENODATA when the requested data to send is empty.
 *  @retval -EBADMSG when the requested data to send is too big.
 *  @retval -ENOBUFS when there are no TX buffers available.
 *  @retval other errno codes from dependent modules.
 */
int icmsg_send(const struct icmsg_config_t *conf,
	       struct icmsg_data_t *dev_data,
	       const void *msg, size_t len);

/**
 * @}
 */

#ifdef __cplusplus
}
#endif

#endif /* ZEPHYR_INCLUDE_IPC_ICMSG_H_ */
