#ifndef _IPC_ICXMSG_COMMON_H_
#define _IPC_ICXMSG_COMMON_H_

#include <zephyr/kernel.h>
#include <zephyr/device.h>

/*
 * In this file, the abbreviation "ICXMsg" refers both ICMsg and ICBMsg.
 */

#define ICXMSG_MINIMUM_THREAD_STACK_SIZE 256

#define ICXMSG_THREAD_TYPE_NONE 1
#define ICXMSG_THREAD_TYPE_DEDICATED 2
#define ICXMSG_THREAD_TYPE_SHARED 3
#define ICXMSG_THREAD_TYPE_SYSTEM 4


// Is enabled
#define _ICXMSG_ENABLED_IT(i, compat, ...) || 1
// Version and compatibility
#define _ICXMSG_VERSION_1_ENABLED_IT(i, compat, ...) || (DT_PROP(DT_INST(i, compat), version) == 1)
#define _ICXMSG_VERSION_2_ENABLED_IT(i, compat, ...) || (DT_PROP(DT_INST(i, compat), version) == 2)
#define _ICXMSG_COMPATIBILITY_ENABLED_IT(i, compat, def) || (COND_CODE_1(DT_NODE_HAS_PROP(DT_INST(i, compat), compatibility), (DT_PROP(DT_INST(i, compat), compatibility)), (def)))
// Thread mode
#define _ICXMSG_NO_THREAD_ENABLED_IT(i, compat, ...) || (CONCAT(ICXMSG_THREAD_TYPE_, DT_STRING_UPPER_TOKEN(DT_INST(i, compat), thread)) == ICXMSG_THREAD_TYPE_NONE)
#define _ICXMSG_DEDICATED_THREAD_ENABLED_IT(i, compat, ...) || (CONCAT(ICXMSG_THREAD_TYPE_, DT_STRING_UPPER_TOKEN(DT_INST(i, compat), thread)) == ICXMSG_THREAD_TYPE_DEDICATED)
#define _ICXMSG_SHARED_THREAD_ENABLED_IT(i, compat, ...) || (CONCAT(ICXMSG_THREAD_TYPE_, DT_STRING_UPPER_TOKEN(DT_INST(i, compat), thread)) == ICXMSG_THREAD_TYPE_SHARED)
#define _ICXMSG_SYSTEM_WORK_QUEUE_ENABLED_IT(i, compat, ...) || (CONCAT(ICXMSG_THREAD_TYPE_, DT_STRING_UPPER_TOKEN(DT_INST(i, compat), thread)) == ICXMSG_THREAD_TYPE_SYSTEM)
// Behaviour between incoming messages
#define _ICXMSG_YIELD_ON_MORE_INPUT_IT(i, compat, ...) || ( \
	(CONCAT(ICXMSG_THREAD_TYPE_, DT_STRING_UPPER_TOKEN(DT_INST(i, compat), thread)) != ICXMSG_THREAD_TYPE_NONE) ? \
	!DT_PROP(DT_INST(i, compat), drain_input) : 0)
#define _ICXMSG_CONTINUE_ON_MORE_INPUT_IT(i, compat, ...) || ( \
	(CONCAT(ICXMSG_THREAD_TYPE_, DT_STRING_UPPER_TOKEN(DT_INST(i, compat), thread)) != ICXMSG_THREAD_TYPE_NONE) ? \
	DT_PROP(DT_INST(i, compat), drain_input) : 0)
// Shared thread properties
#define _ICXMSG_SHARED_THREAD_STACK_SIZE_IT(i, compat, ...) , ( \
	(CONCAT(ICXMSG_THREAD_TYPE_, DT_STRING_UPPER_TOKEN(DT_INST(i, compat), thread)) == ICXMSG_THREAD_TYPE_SHARED) ? \
	DT_PROP(DT_INST(i, compat), thread_stack_size) : 0)
#define _ICXMSG_SHARED_THREAD_PRIORITY_IT(i, compat, ...) , ( \
	(CONCAT(ICXMSG_THREAD_TYPE_, DT_STRING_UPPER_TOKEN(DT_INST(i, compat), thread)) == ICXMSG_THREAD_TYPE_SHARED) ? \
	DT_STRING_UNQUOTED(DT_INST(i, compat), thread_priority) : 1000000000)
// System work queue requirements
#define _ICXMSG_SYSTEM_WORK_QUEUE_STACK_SIZE_IT(i, compat, ...) , ( \
	(CONCAT(ICXMSG_THREAD_TYPE_, DT_STRING_UPPER_TOKEN(DT_INST(i, compat), thread)) == ICXMSG_THREAD_TYPE_SYSTEM) ? \
	DT_PROP(DT_INST(i, compat), thread_stack_size) : 0)
#define _ICXMSG_SYSTEM_WORK_QUEUE_PRIORITY_IT(i, compat, ...) , ( \
	(CONCAT(ICXMSG_THREAD_TYPE_, DT_STRING_UPPER_TOKEN(DT_INST(i, compat), thread)) == ICXMSG_THREAD_TYPE_SYSTEM) ? \
	DT_STRING_UNQUOTED(DT_INST(i, compat), thread_priority) : 1000000000)

#define ICBMSG_ENABLED (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icbmsg, _ICXMSG_ENABLED_IT))
#define ICBMSG_VERSION_1_ENABLED (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icbmsg, _ICXMSG_VERSION_1_ENABLED_IT))
#define ICBMSG_VERSION_2_ENABLED (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icbmsg, _ICXMSG_VERSION_2_ENABLED_IT))
#define ICBMSG_COMPATIBILITY_ENABLED ICBMSG_VERSION_2_ENABLED && (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icbmsg, _ICXMSG_COMPATIBILITY_ENABLED_IT, 0))
#define ICBMSG_NO_THREAD_ENABLED (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icbmsg, _ICXMSG_NO_THREAD_ENABLED_IT))
#define ICBMSG_DEDICATED_THREAD_ENABLED (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icbmsg, _ICXMSG_DEDICATED_THREAD_ENABLED_IT))
#define ICBMSG_SHARED_THREAD_ENABLED (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icbmsg, _ICXMSG_SHARED_THREAD_ENABLED_IT))
#define ICBMSG_SYSTEM_WORK_QUEUE_ENABLED (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icbmsg, _ICXMSG_SYSTEM_WORK_QUEUE_ENABLED_IT))
#define ICBMSG_YIELD_ON_MORE_INPUT (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icbmsg, _ICXMSG_YIELD_ON_MORE_INPUT_IT))
#define ICBMSG_CONTINUE_ON_MORE_INPUT (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icbmsg, _ICXMSG_CONTINUE_ON_MORE_INPUT_IT))
#define ICBMSG_WORKQUEUE_ENABLED (ICBMSG_DEDICATED_THREAD_ENABLED || ICBMSG_SHARED_THREAD_ENABLED || ICBMSG_SYSTEM_WORK_QUEUE_ENABLED)

#define ICMSG_ENABLED (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icmsg, _ICXMSG_ENABLED_IT))
#define ICMSG_VERSION_1_ENABLED (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icmsg, _ICXMSG_VERSION_1_ENABLED_IT))
#define ICMSG_VERSION_2_ENABLED (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icmsg, _ICXMSG_VERSION_2_ENABLED_IT))
#define ICMSG_COMPATIBILITY_ENABLED ICMSG_VERSION_2_ENABLED && (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icmsg, _ICXMSG_COMPATIBILITY_ENABLED_IT, 1))
#define ICMSG_NO_THREAD_ENABLED ICBMSG_ENABLED && (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icmsg, _ICXMSG_NO_THREAD_ENABLED_IT))
#define ICMSG_DEDICATED_THREAD_ENABLED (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icmsg, _ICXMSG_DEDICATED_THREAD_ENABLED_IT))
#define ICMSG_SHARED_THREAD_ENABLED (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icmsg, _ICXMSG_SHARED_THREAD_ENABLED_IT))
#define ICMSG_SYSTEM_WORK_QUEUE_ENABLED (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icmsg, _ICXMSG_SYSTEM_WORK_QUEUE_ENABLED_IT))
#define ICMSG_YIELD_ON_MORE_INPUT (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icmsg, _ICXMSG_YIELD_ON_MORE_INPUT_IT))
#define ICMSG_CONTINUE_ON_MORE_INPUT (0 DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icmsg, _ICXMSG_CONTINUE_ON_MORE_INPUT_IT))
#define ICMSG_WORKQUEUE_ENABLED (ICMSG_DEDICATED_THREAD_ENABLED || ICMSG_SHARED_THREAD_ENABLED || ICMSG_SYSTEM_WORK_QUEUE_ENABLED)

#define ICMSG_SHARED_THREAD_STACK_SIZE MAX_VA(ICXMSG_MINIMUM_THREAD_STACK_SIZE \
	DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icbmsg, _ICXMSG_SHARED_THREAD_STACK_SIZE_IT) \
	DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icmsg, _ICXMSG_SHARED_THREAD_STACK_SIZE_IT))
#define ICMSG_SHARED_THREAD_PRIORITY MIN_VA(1000000000 \
	DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icbmsg, _ICXMSG_SHARED_THREAD_PRIORITY_IT) \
	DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icmsg, _ICXMSG_SHARED_THREAD_PRIORITY_IT))
#define ICMSG_SYSTEM_WORK_QUEUE_STACK_SIZE MAX_VA(ICXMSG_MINIMUM_THREAD_STACK_SIZE \
	DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icbmsg, _ICXMSG_SYSTEM_WORK_QUEUE_STACK_SIZE_IT) \
	DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icmsg, _ICXMSG_SYSTEM_WORK_QUEUE_STACK_SIZE_IT))
#define ICMSG_SYSTEM_WORK_QUEUE_PRIORITY MIN_VA(1000000000 \
	DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icbmsg, _ICXMSG_SYSTEM_WORK_QUEUE_PRIORITY_IT) \
	DT_COMPAT_FOREACH_STATUS_OKAY_VARGS(zephyr_ipc_icmsg, _ICXMSG_SYSTEM_WORK_QUEUE_PRIORITY_IT))

#define ICMSG_SHORT_MESSAGES_ENABLED ICBMSG_ENABLED
#define ICMSG_LONG_MESSAGES_ENABLED ICMSG_ENABLED

#pragma message (STRINGIFY(ICMSG_SYSTEM_WORK_QUEUE_PRIORITY))

/*

#if ICBMSG_SYSTEM_WORK_QUEUE_ENABLED

BUILD_ASSERT(
	_ICXMSG_SYSTEM_WORK_QUEUE_STACK_SIZE <= CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE,
	"Some instance of ICBMsg requires bigger stack for system work queue. "
	"Increase CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE option.");

BUILD_ASSERT(
	_ICXMSG_SYSTEM_WORK_QUEUE_PRIORITY >= CONFIG_SYSTEM_WORKQUEUE_PRIORITY,
	"Some instance of ICBMsg requires higher priority for system work queue. "
	"Set system workqueue priority with the CONFIG_SYSTEM_WORKQUEUE_PRIORITY option, "
	"or reduce priority requirements of ICBMsg instances that are using system workqueue, "
	"or use shared or dedicated thread in ICBMsg.");

#endif

BUILD_ASSERT(
	IS_ENABLED(CONFIG_MULTITHREADING) || (!ICBMSG_SHARED_THREAD_ENABLED &&
	!ICBMSG_DEDICATED_THREAD_ENABLED && !ICBMSG_SYSTEM_WORK_QUEUE_ENABLED),
	"If multithreading is disabled, the device tree \"thread\" property "
	"of ICBMsg must be set to \"none\".");

BUILD_ASSERT(!ICBMSG_COMPATIBILITY_ENABLED,
	"ICBMsg does not support compatibility mode.");

#define ICMSG_SHORT_MESSAGES_ENABLED ICBMSG_ENABLED
#define ICMSG_LONG_MESSAGES_ENABLED ICMSG_ENABLED

*/

#endif /* _IPC_ICXMSG_COMMON_H_ */
