#ifndef _IPC_ICXMSG_COMMON_H_
#define _IPC_ICXMSG_COMMON_H_

#include <zephyr/kernel.h>
#include <zephyr/device.h>

/*
 * In this file, the abbreviation "ICXMsg" refers both ICMsg and ICBMsg.
 */

#define _ICXMSG_MINIMUM_SHARED_THREAD_STACK_SIZE 512

#define _ICXMSG_THREAD_TYPE_NONE 1
#define _ICXMSG_THREAD_TYPE_DEDICATED 2
#define _ICXMSG_THREAD_TYPE_SHARED 3
#define _ICXMSG_THREAD_TYPE_SYSTEM 4

/*
 * The following macros depends on current value of DT_DRV_COMPAT.
 * They will be used to define actual ICMsg and ICBMsg macros and
 * variables that does not depend on DT_DRV_COMPAT.
 */
// Is enabled
#define _ICXMSG_ENABLED_IT(i) || 1
#define _ICXMSG_ENABLED (0 DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_ENABLED_IT))
// Version and compatibility
#define _ICXMSG_VERSION_1_ENABLED_IT(i) || (DT_INST_PROP(i, version) == 1)
#define _ICXMSG_VERSION_1_ENABLED (0 DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_VERSION_1_ENABLED_IT))
#define _ICXMSG_VERSION_2_ENABLED_IT(i) || (DT_INST_PROP(i, version) == 2)
#define _ICXMSG_VERSION_2_ENABLED (0 DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_VERSION_2_ENABLED_IT))
#define _ICXMSG_COMPATIBILITY_ENABLED_IT(i) || (COND_CODE_1(DT_INST_NODE_HAS_PROP(i, compatibility), (DT_INST_PROP(i, compatibility)), (_ICXMSG_VERSION_COMPATIBILITY_DEFAULT)))
#define _ICXMSG_COMPATIBILITY_ENABLED (0 DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_COMPATIBILITY_ENABLED_IT))
// Thread mode
#define _ICXMSG_NO_THREAD_ENABLED_IT(i) || (CONCAT(_ICXMSG_THREAD_TYPE_, DT_INST_STRING_UPPER_TOKEN(i, thread)) == _ICXMSG_THREAD_TYPE_NONE)
#define _ICXMSG_NO_THREAD_ENABLED (0 DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_NO_THREAD_ENABLED_IT))
#define _ICXMSG_DEDICATED_THREAD_ENABLED_IT(i) || (CONCAT(_ICXMSG_THREAD_TYPE_, DT_INST_STRING_UPPER_TOKEN(i, thread)) == _ICXMSG_THREAD_TYPE_DEDICATED)
#define _ICXMSG_DEDICATED_THREAD_ENABLED (0 DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_DEDICATED_THREAD_ENABLED_IT))
#define _ICXMSG_SHARED_THREAD_ENABLED_IT(i) || (CONCAT(_ICXMSG_THREAD_TYPE_, DT_INST_STRING_UPPER_TOKEN(i, thread)) == _ICXMSG_THREAD_TYPE_SHARED)
#define _ICXMSG_SHARED_THREAD_ENABLED (0 DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_SHARED_THREAD_ENABLED_IT))
#define _ICXMSG_SYSTEM_WORK_QUEUE_ENABLED_IT(i) || (CONCAT(_ICXMSG_THREAD_TYPE_, DT_INST_STRING_UPPER_TOKEN(i, thread)) == _ICXMSG_THREAD_TYPE_SYSTEM)
#define _ICXMSG_SYSTEM_WORK_QUEUE_ENABLED (0 DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_SYSTEM_WORK_QUEUE_ENABLED_IT))
// Behaviour between incoming messages
#define _ICXMSG_YIELD_ON_MORE_INPUT_IT(i) || ( \
	(CONCAT(_ICXMSG_THREAD_TYPE_, DT_INST_STRING_UPPER_TOKEN(i, thread)) != _ICXMSG_THREAD_TYPE_NONE) ? \
	!DT_INST_PROP(i, drain_input) : 0)
#define _ICXMSG_YIELD_ON_MORE_INPUT (0 DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_YIELD_ON_MORE_INPUT_IT))
#define _ICXMSG_CONTINUE_ON_MORE_INPUT_IT(i) || ( \
	(CONCAT(_ICXMSG_THREAD_TYPE_, DT_INST_STRING_UPPER_TOKEN(i, thread)) != _ICXMSG_THREAD_TYPE_NONE) ? \
	DT_INST_PROP(i, drain_input) : 0)
#define _ICXMSG_CONTINUE_ON_MORE_INPUT (0 DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_CONTINUE_ON_MORE_INPUT_IT))
// Shared thread properties
#define _ICXMSG_SHARED_THREAD_STACK_SIZE_IT(i) , ( \
	(CONCAT(_ICXMSG_THREAD_TYPE_, DT_INST_STRING_UPPER_TOKEN(i, thread)) == _ICXMSG_THREAD_TYPE_SHARED) ? \
	DT_INST_PROP(i, thread_stack_size) : 0)
#define _ICXMSG_SHARED_THREAD_STACK_SIZE MAX_VA(0 DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_SHARED_THREAD_STACK_SIZE_IT))
#define _ICXMSG_SHARED_THREAD_PRIORITY_IT(i) , ( \
	(CONCAT(_ICXMSG_THREAD_TYPE_, DT_INST_STRING_UPPER_TOKEN(i, thread)) == _ICXMSG_THREAD_TYPE_SHARED) ? \
	DT_INST_STRING_UNQUOTED(i, thread_priority) : 1000000000)
#define _ICXMSG_SHARED_THREAD_PRIORITY MIN_VA(K_LOWEST_APPLICATION_THREAD_PRIO DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_SHARED_THREAD_PRIORITY_IT))
// System work queue requirements
#define _ICXMSG_SYSTEM_WORK_QUEUE_STACK_SIZE_IT(i) , ( \
	(CONCAT(_ICXMSG_THREAD_TYPE_, DT_INST_STRING_UPPER_TOKEN(i, thread)) == _ICXMSG_THREAD_TYPE_SYSTEM) ? \
	DT_INST_PROP(i, thread_stack_size) : 0)
#define _ICXMSG_SYSTEM_WORK_QUEUE_STACK_SIZE MAX_VA(0 DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_SYSTEM_WORK_QUEUE_STACK_SIZE_IT))
#define _ICXMSG_SYSTEM_WORK_QUEUE_PRIORITY_IT(i) , ( \
	(CONCAT(_ICXMSG_THREAD_TYPE_, DT_INST_STRING_UPPER_TOKEN(i, thread)) == _ICXMSG_THREAD_TYPE_SYSTEM) ? \
	DT_INST_STRING_UNQUOTED(i, thread_priority) : 1000000000)
#define _ICXMSG_SYSTEM_WORK_QUEUE_PRIORITY MIN_VA(1000000000 DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_SYSTEM_WORK_QUEUE_PRIORITY_IT))


/* ICBMsg configuration from device tree instances. */

#define DT_DRV_COMPAT zephyr_ipc_icbmsg
#define _ICXMSG_VERSION_COMPATIBILITY_DEFAULT 0

#pragma message ("ICBMSG_ENABLED=" STRINGIFY(_ICXMSG_ENABLED))

#if _ICXMSG_ENABLED
#define ICBMSG_ENABLED 1
#else
#define ICBMSG_ENABLED 0
#endif

#pragma message ("ICBMSG_VERSION_1_ENABLED=" STRINGIFY(_ICXMSG_VERSION_1_ENABLED))

#if _ICXMSG_VERSION_1_ENABLED
#define ICBMSG_VERSION_1_ENABLED 1
#else
#define ICBMSG_VERSION_1_ENABLED 0
#endif

#pragma message ("ICBMSG_VERSION_2_ENABLED=" STRINGIFY(_ICXMSG_VERSION_2_ENABLED))

#if _ICXMSG_VERSION_2_ENABLED
#define ICBMSG_VERSION_2_ENABLED 1
#else
#define ICBMSG_VERSION_2_ENABLED 0
#endif

#pragma message ("ICBMSG_COMPATIBILITY_ENABLED=" STRINGIFY(_ICXMSG_COMPATIBILITY_ENABLED))

#if _ICXMSG_COMPATIBILITY_ENABLED && ICBMSG_VERSION_2_ENABLED
#define ICBMSG_COMPATIBILITY_ENABLED 1
#else
#define ICBMSG_COMPATIBILITY_ENABLED 0
#endif

#pragma message ("ICBMSG_NO_THREAD_ENABLED=" STRINGIFY(_ICXMSG_NO_THREAD_ENABLED))

#if _ICXMSG_NO_THREAD_ENABLED
#define ICBMSG_NO_THREAD_ENABLED 1
#else
#define ICBMSG_NO_THREAD_ENABLED 0
#endif

#pragma message ("ICBMSG_DEDICATED_THREAD_ENABLED=" STRINGIFY(_ICXMSG_DEDICATED_THREAD_ENABLED))

#if _ICXMSG_DEDICATED_THREAD_ENABLED
#define ICBMSG_DEDICATED_THREAD_ENABLED 1
#else
#define ICBMSG_DEDICATED_THREAD_ENABLED 0
#endif

#pragma message ("ICBMSG_SHARED_THREAD_ENABLED=" STRINGIFY(_ICXMSG_SHARED_THREAD_ENABLED))

#if _ICXMSG_SHARED_THREAD_ENABLED
#define ICBMSG_SHARED_THREAD_ENABLED 1
#else
#define ICBMSG_SHARED_THREAD_ENABLED 0
#endif

#pragma message ("ICBMSG_SYSTEM_WORK_QUEUE_ENABLED=" STRINGIFY(_ICXMSG_SYSTEM_WORK_QUEUE_ENABLED))

#if _ICXMSG_SYSTEM_WORK_QUEUE_ENABLED
#define ICBMSG_SYSTEM_WORK_QUEUE_ENABLED 1
#else
#define ICBMSG_SYSTEM_WORK_QUEUE_ENABLED 0
#endif

#pragma message ("ICBMSG_YIELD_ON_MORE_INPUT=" STRINGIFY(_ICXMSG_YIELD_ON_MORE_INPUT))

#if _ICXMSG_YIELD_ON_MORE_INPUT
#define ICBMSG_YIELD_ON_MORE_INPUT 1
#else
#define ICBMSG_YIELD_ON_MORE_INPUT 0
#endif

#pragma message ("ICBMSG_CONTINUE_ON_MORE_INPUT=" STRINGIFY(_ICXMSG_CONTINUE_ON_MORE_INPUT))

#if _ICXMSG_CONTINUE_ON_MORE_INPUT
#define ICBMSG_CONTINUE_ON_MORE_INPUT 1
#else
#define ICBMSG_CONTINUE_ON_MORE_INPUT 0
#endif

#pragma message ("ICBMSG_SHARED_THREAD_PRIORITY=" STRINGIFY(_ICXMSG_SHARED_THREAD_PRIORITY))

static const int icbmsg_shared_thread_priority = _ICXMSG_SHARED_THREAD_PRIORITY;

#if ICBMSG_SYSTEM_WORK_QUEUE_ENABLED

#pragma message ("ICBMSG_SYSTEM_WORK_QUEUE_STACK_SIZE=" STRINGIFY(_ICXMSG_SYSTEM_WORK_QUEUE_STACK_SIZE))

BUILD_ASSERT(
	_ICXMSG_SYSTEM_WORK_QUEUE_STACK_SIZE <= CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE,
	"Some instance of ICBMsg requires bigger stack for system work queue. "
	"Increase CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE option.");

#pragma message ("ICBMSG_SYSTEM_WORK_QUEUE_PRIORITY=" STRINGIFY(_ICXMSG_SYSTEM_WORK_QUEUE_PRIORITY))

BUILD_ASSERT(
	_ICXMSG_SYSTEM_WORK_QUEUE_PRIORITY >= CONFIG_SYSTEM_WORKQUEUE_PRIORITY,
	"Some instance of ICBMsg requires higher priority for system work queue. "
	"Set system workqueue priority with the CONFIG_SYSTEM_WORKQUEUE_PRIORITY option, "
	"or reduce priority requirements of ICBMsg instances that are using system workqueue, "
	"or use shared or dedicated thread in ICBMsg.");

#endif

BUILD_ASSERT(
	IS_ENABLED(CONFIG_MULTITHREADING) || (!ICBMSG_SHARED_THREAD_ENABLED &&
	!ICBMSG_DEDICATED_THREAD_ENABLED && !ICBMSG_SYSTEM_WORK_QUEUE_ENABLED),
	"If multithreading is disabled, the device tree \"thread\" property "
	"of ICBMsg must be set to \"none\".");

BUILD_ASSERT(!ICBMSG_COMPATIBILITY_ENABLED,
	"ICBMsg does not support compatibility mode.");

#undef DT_DRV_COMPAT
#undef _ICXMSG_VERSION_COMPATIBILITY_DEFAULT

/* ICMsg configuration from device tree instances. */

#define DT_DRV_COMPAT zephyr_ipc_icmsg
#define _ICXMSG_VERSION_COMPATIBILITY_DEFAULT 1

#pragma message ("ICMSG_ENABLED=" STRINGIFY(_ICXMSG_ENABLED))

#if _ICXMSG_ENABLED
#define ICMSG_ENABLED 1
#else
#define ICMSG_ENABLED 0
#endif

#pragma message ("ICMSG_VERSION_1_ENABLED=" STRINGIFY(_ICXMSG_VERSION_1_ENABLED))

#if _ICXMSG_VERSION_1_ENABLED
#define ICMSG_VERSION_1_ENABLED 1
#else
#define ICMSG_VERSION_1_ENABLED 0
#endif

#pragma message ("ICMSG_VERSION_2_ENABLED=" STRINGIFY(_ICXMSG_VERSION_2_ENABLED))

#if _ICXMSG_VERSION_2_ENABLED
#define ICMSG_VERSION_2_ENABLED 1
#else
#define ICMSG_VERSION_2_ENABLED 0
#endif

#pragma message ("ICMSG_COMPATIBILITY_ENABLED=" STRINGIFY(_ICXMSG_COMPATIBILITY_ENABLED))

#if _ICXMSG_COMPATIBILITY_ENABLED && ICMSG_VERSION_2_ENABLED
#define ICMSG_COMPATIBILITY_ENABLED 1
#else
#define ICMSG_COMPATIBILITY_ENABLED 0
#endif

#pragma message ("ICMSG_NO_THREAD_ENABLED=" STRINGIFY(_ICXMSG_NO_THREAD_ENABLED))

#if _ICXMSG_NO_THREAD_ENABLED || ICBMSG_ENABLED /* ICBMsg expects callbacks from ISR */
#define ICMSG_NO_THREAD_ENABLED 1
#else
#define ICMSG_NO_THREAD_ENABLED 0
#endif

#pragma message ("ICMSG_DEDICATED_THREAD_ENABLED=" STRINGIFY(_ICXMSG_DEDICATED_THREAD_ENABLED))

#if _ICXMSG_DEDICATED_THREAD_ENABLED
#define ICMSG_DEDICATED_THREAD_ENABLED 1
#else
#define ICMSG_DEDICATED_THREAD_ENABLED 0
#endif

#pragma message ("ICMSG_SHARED_THREAD_ENABLED=" STRINGIFY(_ICXMSG_SHARED_THREAD_ENABLED))

#if _ICXMSG_SHARED_THREAD_ENABLED
#define ICMSG_SHARED_THREAD_ENABLED 1
#else
#define ICMSG_SHARED_THREAD_ENABLED 0
#endif

#pragma message ("ICMSG_SYSTEM_WORK_QUEUE_ENABLED=" STRINGIFY(_ICXMSG_SYSTEM_WORK_QUEUE_ENABLED))

#if _ICXMSG_SYSTEM_WORK_QUEUE_ENABLED
#define ICMSG_SYSTEM_WORK_QUEUE_ENABLED 1
#else
#define ICMSG_SYSTEM_WORK_QUEUE_ENABLED 0
#endif

#pragma message ("ICMSG_YIELD_ON_MORE_INPUT=" STRINGIFY(_ICXMSG_YIELD_ON_MORE_INPUT))

#if _ICXMSG_YIELD_ON_MORE_INPUT
#define ICMSG_YIELD_ON_MORE_INPUT 1
#else
#define ICMSG_YIELD_ON_MORE_INPUT 0
#endif

#pragma message ("ICMSG_CONTINUE_ON_MORE_INPUT=" STRINGIFY(_ICXMSG_CONTINUE_ON_MORE_INPUT))

#if _ICXMSG_CONTINUE_ON_MORE_INPUT
#define ICMSG_CONTINUE_ON_MORE_INPUT 1
#else
#define ICMSG_CONTINUE_ON_MORE_INPUT 0
#endif

#pragma message ("ICMSG_SHARED_THREAD_PRIORITY=" STRINGIFY(_ICXMSG_SHARED_THREAD_PRIORITY))

static const int icmsg_shared_thread_priority = _ICXMSG_SHARED_THREAD_PRIORITY;

#if ICMSG_SYSTEM_WORK_QUEUE_ENABLED

#pragma message ("ICMSG_SYSTEM_WORK_QUEUE_STACK_SIZE=" STRINGIFY(_ICXMSG_SYSTEM_WORK_QUEUE_STACK_SIZE))

BUILD_ASSERT(
	_ICXMSG_SYSTEM_WORK_QUEUE_STACK_SIZE <= CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE,
	"Some instance of ICMsg requires bigger stack for system work queue. "
	"Increase CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE option.");

#pragma message ("ICMSG_SYSTEM_WORK_QUEUE_PRIORITY=" STRINGIFY(_ICXMSG_SYSTEM_WORK_QUEUE_PRIORITY))

BUILD_ASSERT(
	_ICXMSG_SYSTEM_WORK_QUEUE_PRIORITY >= CONFIG_SYSTEM_WORKQUEUE_PRIORITY,
	"Some instance of ICMsg requires higher priority for system work queue. "
	"Set system workqueue priority with the CONFIG_SYSTEM_WORKQUEUE_PRIORITY option, "
	"or reduce priority requirements of ICMsg instances that are using system workqueue, "
	"or use shared or dedicated thread in ICMsg.");

#endif

BUILD_ASSERT(
	IS_ENABLED(CONFIG_MULTITHREADING) || (!ICMSG_SHARED_THREAD_ENABLED &&
	!ICMSG_DEDICATED_THREAD_ENABLED && !ICMSG_SYSTEM_WORK_QUEUE_ENABLED),
	"If multithreading is disabled, the device tree \"thread\" property "
	"of ICMsg must be set to \"none\".");

#define ICMSG_SHORT_MESSAGES_ENABLED ICBMSG_ENABLED
#define ICMSG_LONG_MESSAGES_ENABLED ICMSG_ENABLED

#undef DT_DRV_COMPAT
#undef _ICXMSG_VERSION_COMPATIBILITY_DEFAULT

/* Nasty trick to make ICMSG_SHARED_THREAD_STACK_SIZE independent from DT_DRV_COMPAT */
#define DT_DRV_COMPAT zephyr_ipc_icmsg
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & 0x1F
#define _ICMSG_SHARED_THREAD_STACK_SIZE_LOWER_BITS 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 5)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_5 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 6)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_6 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 7)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_7 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 8)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_8 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 9)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_9 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 10)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_10 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 11)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_11 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 12)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_12 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 13)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_13 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 14)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_14 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 15)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_15 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 16)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_16 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 17)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_17 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 18)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_18 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 19)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_19 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 20)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_20 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 21)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_21 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 22)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_22 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 23)
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BIT_23 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & 0xFF000000
#error Unsupported stack size
#endif
#define _ICMSG_SHARED_THREAD_STACK_SIZE_BITS_IT(i) COND_CODE_1(IS_ENABLED(CONCAT(_ICMSG_SHARED_THREAD_STACK_SIZE_BIT_, i)), ((1 << i)), (0))
#define ICMSG_SHARED_THREAD_STACK_SIZE \
	(IS_ENABLED(_ICMSG_SHARED_THREAD_STACK_SIZE_LOWER_BITS) ? 0x20 : 0) + \
	FOR_EACH(_ICMSG_SHARED_THREAD_STACK_SIZE_BITS_IT, (+), \
	5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23)
#undef DT_DRV_COMPAT


/* Nasty trick to make ICBMSG_SHARED_THREAD_STACK_SIZE independent from DT_DRV_COMPAT */
#define DT_DRV_COMPAT zephyr_ipc_icbmsg
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & 0x1F
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_LOWER_BITS 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 5)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_5 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 6)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_6 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 7)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_7 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 8)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_8 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 9)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_9 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 10)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_10 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 11)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_11 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 12)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_12 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 13)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_13 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 14)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_14 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 15)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_15 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 16)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_16 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 17)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_17 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 18)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_18 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 19)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_19 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 20)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_20 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 21)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_21 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 22)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_22 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & (1 << 23)
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_23 1
#endif
#if _ICXMSG_SHARED_THREAD_STACK_SIZE & 0xFF000000
#error Unsupported stack size
#endif
#define _ICBMSG_SHARED_THREAD_STACK_SIZE_BITS_IT(i) COND_CODE_1(IS_ENABLED(CONCAT(_ICBMSG_SHARED_THREAD_STACK_SIZE_BIT_, i)), ((1 << i)), (0))
#define ICBMSG_SHARED_THREAD_STACK_SIZE \
	(IS_ENABLED(_ICBMSG_SHARED_THREAD_STACK_SIZE_LOWER_BITS) ? 0x20 : 0) + \
	FOR_EACH(_ICBMSG_SHARED_THREAD_STACK_SIZE_BITS_IT, (+), \
	5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23)
#undef DT_DRV_COMPAT

#pragma message ("ICMSG_SHARED_THREAD_STACK_SIZE=" STRINGIFY(ICMSG_SHARED_THREAD_STACK_SIZE))
#pragma message ("ICBMSG_SHARED_THREAD_STACK_SIZE=" STRINGIFY(ICBMSG_SHARED_THREAD_STACK_SIZE))


#if 0
#pragma message ("ICBMSG_VERSION_1_ENABLED is " TO_STRING(ICBMSG_VERSION_1_ENABLED) " == " TO_STRING(DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_VERSION_1_ENABLED)))
#pragma message ("ICBMSG_VERSION_2_ENABLED is " TO_STRING(ICBMSG_VERSION_2_ENABLED) " == " TO_STRING(DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_VERSION_2_ENABLED)))
#pragma message ("ICBMSG_COMPATIBILITY_ENABLED is " TO_STRING(ICBMSG_COMPATIBILITY_ENABLED) " == " TO_STRING(DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_COMPATIBILITY_ENABLED)))
#pragma message ("ICBMSG_NO_THREAD_ENABLED is " TO_STRING(ICBMSG_NO_THREAD_ENABLED) " == " TO_STRING(DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_NO_THREAD_ENABLED)))
#pragma message ("ICBMSG_DEDICATED_THREAD_ENABLED is " TO_STRING(ICBMSG_DEDICATED_THREAD_ENABLED) " == " TO_STRING(DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_DEDICATED_THREAD_ENABLED)))
#pragma message ("ICBMSG_SHARED_THREAD_ENABLED is " TO_STRING(ICBMSG_SHARED_THREAD_ENABLED) " == " TO_STRING(DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_SHARED_THREAD_ENABLED)))
#pragma message ("ICBMSG_SYSTEM_WORK_QUEUE_ENABLED is " TO_STRING(ICBMSG_SYSTEM_WORK_QUEUE_ENABLED) " == " TO_STRING(DT_INST_FOREACH_STATUS_OKAY(_ICXMSG_SYSTEM_WORK_QUEUE_ENABLED)))
#pragma message ("MAX is " TO_STRING(MAX_VA(1, 2)))
#endif

#endif /* _IPC_ICXMSG_COMMON_H_ */
