name: Coding Guidelines

on: pull_request

jobs:
  compliance_job:
    runs-on: ubuntu-22.04
    name: Run coding guidelines checks on patch series (PR)
    steps:
    - name: Install python dependencies
      run: |
        echo '::error file=zephyr/.github/workflows/coding_guidelines.yml,line=7,title=API-Check Critical:: :red_circle: Field "usage" deleted from structure "pm_device".'
